// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	courses "Github.com/NaujOyamat/microservice-template/internal/domain/courses"
	mock "github.com/stretchr/testify/mock"
)

// ICourseRepository is an autogenerated mock type for the ICourseRepository type
type ICourseRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, course
func (_m *ICourseRepository) Save(ctx context.Context, course *courses.Course) error {
	ret := _m.Called(ctx, course)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *courses.Course) error); ok {
		r0 = rf(ctx, course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
